services:
  client:
    build: ./client
    ports:
      - "30000:80"  # Use 30000 for local port instead of 3000 to not conflict with any local development
    depends_on:
      - server
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  server:
    build: ./server
    ports:
      - "50000:5000" # Use 50000 for local port instead of 5000 to not conflict with any existing local development
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=tool_library_db
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=production
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tool_library_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./logs:/var/log/postgresql
    ports:
      - "54321:5432"  # Use 54321 for local port instead of 5432 to not conflict with any local development
    restart: unless-stopped

volumes:
  postgres_data:
